export const TOPICS = {
  CONSULTAR_JOGADORES: 'consultar-jogadores',
  CRIAR_JOGADORES: 'criar-jogador',
  ATUALIZAR_JOGADOR: 'atualizar-jogador',
  CRIAR_JOGADOR: 'criar-jogador',
  CRIAR_CATEGORIA: 'criar-categoria',
  CONSULTAR_CATEGORIAS: 'consultar-categorias',
  ATUALIZAR_CATEGORIA: 'atualizar-categoria',
  DELETAR_CATEGORIA: 'deletar-categoria',
  DELETAR_JOGADOR: 'deletar-jogador',
  CRIAR_DESAFIO: 'criar-desafio',
  CONSULTAR_DESAFIOS: 'consultar-desafios',
  ATUALIZAR_DESAFIO: 'atualizar-desafio',
  CONSULTAR_DESAFIOS_REALIZADOS: 'consultar-desafios-realizados',
  DELETAR_DESAFIO: 'deletar-desafio',
  CRIAR_PARTIDA: 'criar-partida',
  ATUALIZAR_DESAFIO_PARTIDA: 'atualizar-desafio-partida',
  PROCESSAR_PARTIDA:"processar-partida",
  CONSULTAR_RANKINGS:"consultar-rankings"
};
